name: Deploy Infrastructure on AWS

on:
  push:
    branches:
      - development
      - staging
      - production

jobs:
  run_deploy:
    uses: Americas-Health-AKCIT/infra-pipelines/.github/workflows/terraform.yml@main
    with:
      environment: ${{ github.ref_name }}
    secrets: inherit